excluded:
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData
  - libs
  - Libs
  - test_build

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - unused_capture_list

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - vertical_parameter_alignment_on_call
  - yoda_condition

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

force_unwrapping: error
force_cast: error
force_try: error
legacy_hashing: error

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  
function_body_length:
    warning: 40
    error: 80
    
type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200
 
vertical_whitespace:
  max_empty_lines: 1


trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
  
indentation_width:
  indentation_width: 4
  include_comments: false # XCode auto indent (control + i) for multiline comment always triggers this warning

identifier_name:
  excluded:
    - id
    - x
    - y
    - z
    - URL
    - GlobalAPIKey

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true
  
private_over_fileprivate:
  validate_extensions: true
